/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* boiler environment flag */
#define BOILER_ENVIRONMENT 1

/* boiler environment version */
#define BOILER_VERSION 1.0

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* dl usability */
#define HAVE_LIBdl 1

/* epoll usability */
#define HAVE_LIBepoll 1

/* hot usability */
#define HAVE_LIBhot 1

/* kqueue usability */
/* #undef HAVE_LIBkqueue */

/* libxml2 usability */
#define HAVE_LIBlibxml2 1

/* rt usability */
/* #undef HAVE_LIBrt */

/* use linux threads */
/* #undef HAVE_LTHREADS */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* use pthreads */
#define HAVE_PTHREADS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */

/* Define to the address where bug reports for this package should be sent. */

/* Define to the full name of this package. */

/* Define to the full name and version of this package. */

/* Define to the one symbol short name of this package. */

/* Define to the version of this package. */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* system configuration directory */
#define SYSCONFDIR "/home/virtan/tests/etc"

/* one thread per client mode - for portability purposes */
#define THREAD_PER_CLIENT_MODE 1

/* Version number of package */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
